<?php

namespace Dashed\DashedCore\Filament\Resources\Reviews\Pages;

use Filament\Resources\Pages\CreateRecord;
use Dashed\DashedCore\Filament\Resources\Reviews\ReviewResource;

class CreateReview extends CreateRecord
{
    protected static string $resource = ReviewResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['provider'] = 'own';

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
